<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Address Book</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <body data-records='<?= $records ?>'>
        <div class="body">
            <app-root></app-root>
        </div>
        <script type="text/javascript" src="/dist/runtime.js"></script>
        <script type="text/javascript" src="/dist/polyfills.js"></script>
        <script type="text/javascript" src="/dist/styles.js"></script>
        <script type="text/javascript" src="/dist/vendor.js"></script>
        <script type="text/javascript" src="/dist/main.js"></script>
    </body>
</html>
